### ISSUE TITLE
(gosdk download file) err:Download failed for block 1; no shard data

### ISSUE THREAD

**Issue by boddumanohar** [0chain/gosdk#864] opened 2023-03-27 10:51 UTC
steps to reproduce: 

In wasm demo, 
1. perform an file upload
2. try to download the file from the same wallet

**Comment by cnlangzi** [comment] 2023-04-12 07:23
@boddumanohar  it is caused by mismatched version. please upgrade everything(gosdk/wasmsdk/blobber/...) to latest staging.

**Comment by cnlangzi** [comment] 2023-04-13 09:32
close it now. please feel free to re-open it if it happens again

**Closed as completed by cnlangzi** 2023-04-13 09:32 UTC
